name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm build

    #  - name: Publish to npm
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    #    run: pnpm publish
